version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
    environment:
      - MODEL_PATH=/app/models/model.pkl
    command: uvicorn api.main:app --host 0.0.0.0 --port 8000

  jupyter:
    build:
      context: .
      dockerfile: docker/Dockerfile.jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/app
    command: jupyter notebook --ip=0.0.0.0 --port=8888 --no-browser --allow-root

  train:
    build:
      context: .
      dockerfile: docker/Dockerfile.train
    volumes:
      - ./models:/app/models
    command: python leanai/modeling/train.py
